services:
  owui-metering:
    build: .
    image: swip3798/owui-metering
    container_name: owui-metering
    env_file: '.env'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:45000/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 10
